server:
  port: 8080
  servlet:
    context-path: /pavel

management:
  endpoints:
    web:
      exposure:
        include: 'info, health, metrics, prometheus, heapdump, scheduledtasks, logfile, loggers, mappings'

spring:
  datasource:
    url: jdbc:tc:postgresql:11:///test
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create